<!DOCTYPE html>

<html>
	<head>
		<title>TInyAuth | Privacy Policy</title>
		<style>
			#main {width:70%; margin:auto; border-left:2px solid blue; border-right:2px solid blue;}
			p {margin:20px; text-indent:20px;}
			h4 {margin:0 20px;}
		</style>
	</head>
	<body>
		<div id="main">
			<h4>Preamble</h5>
			<p>This policy governs the handling of &quot;personally-identifiable information&quot; by Project TInyAuth such that end users may be properly informed on what information this service requires and transmits, the purpose for and usage of that information, and the expectations users should have of privacy and security. If you have any questions, please do not hesitate to contact us via any of the options provided on the <a href="contact.php">contact page</a> (pending - WIP).</p>
			<h4>Collection and Dissemination</h5>
			<p>The Project collects some personally-identifiable information, namely a username and password that is (hopefully) unique to this service and an email address. All other information associated with your account is generated internally by the API and are cryptographic secrets, usually random, used to facilitate the sole function of this service--universal authentication for account-based services targeting the TI-84+ CE.</p>
			<p>At no point is the information you provide broadcast publicly. Username and password are solely used to authenticate future attempts to login to your account. Your email address is only used for the purposes of account rescue should you forget your password, two-factor authentication (implementation pending), and in rare instances to inform of major changes to the Service that will impact users. Information associated with your account will not be shared with any external parties for any reason. You have the right to request that your account information be removed from our records via the &quot;Delete Account&quot; button accessible from your user profile. Additionally, you have the ability to refresh your account secret token via the &quot;Refresh User Token&quot; button accessible while logged in. This immediately revokes any TInyAuth keyfiles that have been generated by this service prior to this point.</p>
			<p>At your discretion you can use your account profile to generate a signed keyfile for your TI-84+ CE graphing calculator. This keyfile contains your account id (username) as well as a <a href="https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm" target="_blank">signed</a> authentication token generated from your account secret. The signing of this token allows for the Service to verify its integrity and authenticity. These downloadable files are in the form of TI Application Variables (.8xv), which are files compatible with the TI-84+ CE. Services that support the use of TInyAuth for authentication must request that your device send the keyfile in all or in part. The authenticating service will then parse the keyfile to extract your account id and the signed token. Those credentials must then be transmited to the TInyAuth Service via a GET request. The entire TInyAuth website, including the authentication component, runs over SSL and therefore all end-to-end traffic is encrypted.</p>
			<h4>COPPA Compliance</h4>
			<p>The Service is open to use by anyone of any age with a TI-84+ CE graphing calculator that they make use of in such an advanced fashion. While most members of the tech community relish the opportunity to inspire young minds with the nuances of what technology can do and how to push its limits, we also understand that parents have very real cause to be concerned when their children use Internet services, especially those they are unfamiliar with. If you are a parent whose child is interested in using (or has already made use of) this service, are concerned about what they may have shared and what use it is put to, and would like more information than is provided herein (or even to request it be deleted), feel free to <a href="contact.php">contact us</a>.</p>
		</div>
	</body>
</html>
